services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma migrate deploy && npm start"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      bash -c "
        echo POSTGRES_USER=$${POSTGRES_USER} &&
        echo POSTGRES_PASSWORD=$${POSTGRES_PASSWORD} &&
        echo POSTGRES_DB=$${POSTGRES_DB} &&
        docker-entrypoint.sh postgres
      "

volumes:
  postgres-data: